server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api/v2

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: doodledoodle
      enable-auto-commit: false
      auto-offset-reset: earliest
    retry:
      topic:
        enabled: false
        attempts: 0

  logging:
    level:
      com:
        amazonaws:
          util:
            EC2MetadataUtils: error
