server:
  servlet:
    context-path: /api/v2

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: src/main/resources/files
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: DoodleDoodle

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: doodle-bucket
      dir: /image
      region:
        static: ap-northeast-2
      default-path: images
      uri: https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/

    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false