server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api/v2

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
    consumer:
      group-id: doodle
      enable-auto-commit: false
      auto-offset-reset: earliest
    retry:
      topic:
        enabled: false
        attempts: 0

  logging:
    level:
      com:
        amazonaws:
          util:
            EC2MetadataUtils: error

cloud:
  aws:
    s3:
      #      bucket: doodle-bucket
      bucket: test-bucket-doodle
      dir: /image
      region:
        static: ap-northeast-2
      default-path: images
      #      uri: https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/
      uri: https://test-bucket-doodle.s3.ap-northeast-2.amazonaws.com/

    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false