insert into dictionary(id, korean_name, english_name, image_url) values
                                                                (1, '알람 시계', 'alarm_clock', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/alarm_clock.png'),
                                                                (2, '확성기', 'megaphone', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/megaphone.png'),
                                                                (3, '카누', 'canoe', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/canoe.png'),
                                                                (4, '망치', 'hammer', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/hammer.png'),
                                                                (5, '티셔츠', 't-shirt', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/t-shirt.png'),
                                                                (6, '찻주전자', 'teapot', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/teapot.png'),
                                                                (7, '육각형', 'hexagon', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/hexagon.png'),
                                                                (8, '우산', 'umbrella', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/umbrella.png'),
                                                                (9, '삼각형', 'triangle', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/triangle.png'),
                                                                (10, '포크', 'fork', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/fork.png'),
                                                                (11, '의자', 'chair', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/chair.png'),
                                                                (12, '벤치', 'bench', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/bench.png'),
                                                                (13, '바구니', 'bucket', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/bucket.png'),
                                                                (14, '시소', 'see_saw', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/see_saw.png'),
                                                                (15, '세탁기', 'washing_machine', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/washing_machine.png'),
                                                                (16, '교회', 'church', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/church.png'),
                                                                (17, '도끼', 'axe', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/axe.png'),
                                                                (18, '숟가락', 'spoon', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/spoon.png'),
                                                                (19, '여행 가방', 'suitcase', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/suitcase.png'),
                                                                (20, '문', 'door', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/door.png'),
                                                                (21, '그네', 'swing_set', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/swing_set.png'),
                                                                (22, '바지', 'pants', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/pants.png'),
                                                                (23, '버섯', 'mushroom', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/mushroom.png'),
                                                                (24, '침상', 'couch', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/couch.png'),
                                                                (25, '뱀', 'snake', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/snake.png'),
                                                                (26, '청진기', 'stethoscope', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/stethoscope.png'),
                                                                (27, '헤드폰', 'headphones', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/headphones.png'),
                                                                (28, '꽃', 'flower', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/flower.png'),
                                                                (29, '책', 'book', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/book.png'),
                                                                (30, '테이블', 'table', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/table.png'),
                                                                (31, '무지개', 'rainbow', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/rainbow.png'),
                                                                (32, '양말', 'sock', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/sock.png'),
                                                                (33, '연필', 'pencil', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/pencil.png'),
                                                                (34, '눈송이', 'snowflake', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/snowflake.png'),
                                                                (35, '왕관', 'crown', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/crown.png'),
                                                                (36, '액자', 'picture_frame', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/picture_frame.png'),
                                                                (37, '욕조', 'bathtub', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/bathtub.png'),
                                                                (38, '플래시', 'flashlight', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/flashlight.png'),
                                                                (39, '송곳', 'drill', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/drill.png'),
                                                                (40, '베개', 'pillow', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/pillow.png'),
                                                                (41, '교량', 'bridge', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/bridge.png'),
                                                                (42, '이빨', 'tooth', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/tooth.png'),
                                                                (43, '아령', 'dumbbell', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/dumbbell.png'),
                                                                (44, '안경', 'eyeglasses', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/eyeglasses.png'),
                                                                (45, '다이아몬드', 'diamond', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/diamond.png'),
                                                                (46, '신호등', 'traffic_light', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/traffic_light.png'),
                                                                (47, '구두', 'shoe', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/shoe.png'),
                                                                (48, '텐트', 'tent', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/tent.png'),
                                                                (49, '장롱', 'dresser', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/dresser.png'),
                                                                (50, '열쇠', 'key', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/key.png'),
                                                                (51, '정사각형', 'square', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/square.png'),
                                                                (52, '자전거', 'bicycle', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/bicycle.png'),
                                                                (53, '칼', 'knife', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/knife.png'),
                                                                (54, '야구공', 'baseball', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/baseball.png'),
                                                                (55, '검', 'sword', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/sword.png'),
                                                                (56, '텔레비전', 'television', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/television.png'),
                                                                (57, '나무', 'tree', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/tree.png'),
                                                                (58, '잎', 'leaf', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/leaf.png'),
                                                                (59, '종이 클립', 'paper_clip', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/paper_clip.png'),
                                                                (60, '양초', 'candle', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/candle.png'),
                                                                (61, '휴대전화', 'cell_phone', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/cell_phone.png'),
                                                                (62, '양', 'sheep', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/sheep.png'),
                                                                (63, '사서함', 'mailbox', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/mailbox.png'),
                                                                (64, '선인장', 'cactus', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/cactus.png'),
                                                                (65, '와인 잔', 'wine_glass', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/wine_glass.png'),
                                                                (66, '배(과일)', 'pear', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/pear.png'),
                                                                (67, '프라이팬', 'frying_pan', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/frying_pan.png'),
                                                                (68, '산', 'mountain', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/mountain.png'),
                                                                (69, '톱', 'saw', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/saw.png'),
                                                                (70, '아이스크림', 'ice_cream', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/ice_cream.png'),
                                                                (71, '바퀴', 'wheel', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/wheel.png'),
                                                                (72, '나비', 'butterfly', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/butterfly.png'),
                                                                (73, '플로어 램프', 'floor_lamp', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/floor_lamp.png'),
                                                                (74, '요트', 'sailboat', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/sailboat.png'),
                                                                (75, '캥거루', 'kangaroo', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/kangaroo.png'),
                                                                (76, '도넛', 'donut', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/donut.png'),
                                                                (77, '별', 'star', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/star.png'),
                                                                (78, '사과', 'apple', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/apple.png'),
                                                                (79, '생일 케이크', 'birthday_cake', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/birthday_cake.png'),
                                                                (80, '햄버거', 'hamburger', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/hamburger.png'),
                                                                (81, '바나나', 'banana', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/banana.png'),
                                                                (82, '열기구', 'hot_air_balloon', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/hot_air_balloon.png'),
                                                                (83, '롤러 스케이트', 'rollerskates', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/rollerskates.png'),
                                                                (84, '집', 'house', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/house.png'),
                                                                (85, '땅콩', 'peanut', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/peanut.png'),
                                                                (86, '스케이트보드', 'skateboard', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/skateboard.png'),
                                                                (87, '눈사람', 'snowman', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/snowman.png'),
                                                                (88, '부메랑', 'boomerang', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/boomerang.png'),
                                                                (89, '와인 병', 'wine_bottle', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/wine_bottle.png'),
                                                                (90, '페인트 통', 'paint_can', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/paint_can.png'),
                                                                (91, '비행기', 'airplane', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/airplane.png'),
                                                                (92, '전구', 'light_bulb', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/light_bulb.png'),
                                                                (93, '골프 클럽', 'golf_club', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/golf_club.png'),
                                                                (94, '컵', 'cup', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/cup.png'),
                                                                (95, '모래시계', 'hourglass', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/hourglass.png'),
                                                                (96, '생선', 'fish', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/fish.png'),
                                                                (97, '꽃병', 'vase', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/vase.png'),
                                                                (98, '자동차', 'car', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/car.png'),
                                                                (99, '모자', 'hat', 'https://doodle-bucket.s3.ap-northeast-2.amazonaws.com/image/hat.png');
